### ISSUE TITLE
Got the .db, how to generate the 3D map like yours?

### ISSUE THREAD

**Issue by pat-CIMAR-UF** [Beshario/SLAM-map-my-world#1]
Hi,
I am also one of the Udacity Robotics Software Engineer students. For this project, I already generated my .db data, but how could I generate the 3D map result like yours in RTAB-Map database viewer?
Many thanks.

**Comment by Beshario** [comment]
Hi I remember that I used rtabmap databaseViewer
a command line like
''' rtabmap- databaseViewer <filename.db>''' 
should view your database in the viewer, good luck

check https://github.com/introlab/rtabmap/wiki/Tools

**Comment by pat-CIMAR-UF** [comment]
Thanks
